"""Add hospital quality columns

Revision ID: 7840094039e0
Revises: 
Create Date: 2026-07-31 15:38:11.324789

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7840094039e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_quality', sa.Column('mortality_group_measure_count', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('mortality_facility_measure_count', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('mortality_better', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('mortality_no_different', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('mortality_worse', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('safety_group_measure_count', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('safety_facility_measure_count', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('safety_better', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('safety_no_different', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('safety_worse', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('readmission_group_measure_count', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('readmission_facility_measure_count', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('readmission_better', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('readmission_no_different', sa.Integer(), nullable=True))
    op.add_column('hospital_quality', sa.Column('readmission_worse', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital_quality', 'readmission_worse')
    op.drop_column('hospital_quality', 'readmission_no_different')
    op.drop_column('hospital_quality', 'readmission_better')
    op.drop_column('hospital_quality', 'readmission_facility_measure_count')
    op.drop_column('hospital_quality', 'readmission_group_measure_count')
    op.drop_column('hospital_quality', 'safety_worse')
    op.drop_column('hospital_quality', 'safety_no_different')
    op.drop_column('hospital_quality', 'safety_better')
    op.drop_column('hospital_quality', 'safety_facility_measure_count')
    op.drop_column('hospital_quality', 'safety_group_measure_count')
    op.drop_column('hospital_quality', 'mortality_worse')
    op.drop_column('hospital_quality', 'mortality_no_different')
    op.drop_column('hospital_quality', 'mortality_better')
    op.drop_column('hospital_quality', 'mortality_facility_measure_count')
    op.drop_column('hospital_quality', 'mortality_group_measure_count')
    # ### end Alembic commands ###